version: 0.2

phases:
  pre_build:
    commands:
      - echo Build Starting...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo DOCKER PATH 362787105273.dkr.ecr.us-east-1.amazonaws.com/bittensor-api:latest
      - docker build -t 362787105273.dkr.ecr.us-east-1.amazonaws.com/bittensor-api:latest .
      - docker tag 362787105273.dkr.ecr.us-east-1.amazonaws.com/bittensor-api:latest 362787105273.dkr.ecr.us-east-1.amazonaws.com/bittensor-api:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - aws --version
      - eval $(aws ecr get-login --region us-east-1 --no-include-email | sed 's|https://||')
      - echo Pushing the Docker images...
      - docker push 362787105273.dkr.ecr.us-east-1.amazonaws.com/bittensor-api:latest
      - echo Writing image definitions file...
      - printf '[{"name":"fast-api","imageUri":"%s"}]' 362787105273.dkr.ecr.us-east-1.amazonaws.com/bittensor-api:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

artifacts:
  files: imagedefinitions.json